### ISSUE TITLE
Fake WS281x driver is compiled on Raspberry Pi

### ISSUE THREAD

**Issue by schrockwell** [GregMefford/blinkchain#17]
I have a Raspberry Pi running plain old Raspbian Jessie, with Erlang and Elixir installed per the directions on the Elixir site. In other words, no Nerves is involved here.

When compiling a mix project that uses Blinkchain on the Pi, the `rpi_ws281x` driver application is compiled in "fake" mode, and it does not communicate with the NeoPixels at all.

The problem is due to these lines in the Makefile - it is expecting the environment variable `$CROSSCOMPILE` to be defined:

```make
ifeq ($(CROSSCOMPILE),)
# Host testing build
CFLAGS += -DDEBUG
SRC = src/rpi_ws281x.c src/fake_ws2811.c
endif
ifneq ($(CROSSCOMPILE),)
# Normal build
SRC = src/rpi_ws281x.c src/rpi_ws281x/dma.c src/rpi_ws281x/mailbox.c \
	src/rpi_ws281x/mailbox.c src/rpi_ws281x/pwm.c src/rpi_ws281x/rpihw.c \
	src/rpi_ws281x/pcm.c src/rpi_ws281x/ws2811.c
endif
```

My hacky solution was:
```
mix deps.clean blinkchain
CROSSCOMPILE=1 mix compile
```

**Comment by GregMefford** [comment]
As of `blinkchain` v1.0.0, when you compile outside of the normal Nerves firmware workflow, it shows a warning message like this:
```
Makefile:53: No cross-compiler detected. Building Blinkchain native code in test mode.
Makefile:53: If you were intending to build in normal mode e.g. directly on a Raspberry Pi,
Makefile:53: you can force it by running `CROSS_COMPILE=true mix compile`
```

**Comment by schrockwell** [comment]
Great! Thanks for addressing this!
