### ISSUE TITLE
README has not been updated to reflect 0.3.0

### ISSUE THREAD

**Issue by Serneum** [GregMefford/blinkchain#3]
[Hex](https://libraries.io/hex/nerves_neopixel) lists nerves_neopixel as version `0.3.0` but the README shows configuration with version `0.1.0`. `0.3.0` is also not listed under "Releases" for the GitHub repository

It looks like #2 already tries to fix this but specifically points to GitHub which may not be ideal.

It also looks like the examples use the old 0.1.0 and 0.2.0 code (nerves_io_neopixel) and the code has changed quite drastically since then

**Comment by GregMefford** [comment]
Thanks for taking the time to point this out. It looks like I missed a few steps when doing the most-recent release. I am already working on cleaning up the NeoPixel example along with all the other examples over on https://github.com/nerves-project/nerves-examples so I'll be sure to get this cleaned up as well.

**Comment by GregMefford** [comment]
I finally got around to spending a little time updating this library and the docs should be synced up now!
