### ISSUE TITLE
RGBW support

### ISSUE THREAD

**Issue by CaptChrisD** [GregMefford/blinkchain#5]
Been thinking about an LED project lately and noticed the newer RGBW neopixels (https://www.adafruit.com/products/2842)

I can probably hack my way though this but thought it might be easier to ask for some help.

Still not 100% sure I have time to do the project, but sure would be nice to support these newer leds

It looks like the linked project does have support for RGBW which is nice

**Comment by GregMefford** [comment]
Just wanted to let you know that I've been working on this, but I don't currently have any RGBW NeoPixels to test with. Did you buy some yet? There's someone on Slack that I've been working with, but it's always good to have some more testers available until I can get some for myself.

**Comment by GregMefford** [comment]
For anyone following this issue, there is a branch that supports RGBW NeoPixels, but I haven't gotten around to finalizing a release that includes it. https://github.com/GregMefford/nerves_neopixel/tree/rgbw

In the meantime, you should be able to try it by using this in your deps:

`{:nerves_neopixel, github: "GregMefford/nerves_neopixel", branch: "rgbw", submodules: true}`

**Comment by GregMefford** [comment]
Finally resolved by #15 (along with a complete re-write of just about everything) 🎉
