### ISSUE TITLE
Update deps

### ISSUE THREAD

**Issue by type1fool** [GregMefford/blinkchain#6]
The :elixir_make dep needs to be updated to 0.4 to be compatible with other nerves packages without override.

For example: 

> Failed to use "elixir_make" (version 0.4.0) because
>   nerves_neopixel (version 0.3.0) requires ~> 0.3.0
>   nerves_network (version 0.3.3) requires ~> 0.4
>   nerves_runtime (version 0.4.3) requires ~> 0.4
>   mix.lock specifies 0.4.0

**Comment by GregMefford** [comment]
Thanks for posting this issue. I've released `v0.3.1` that fixes this issue! 🎈 🚀
